apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: scalingpolicies.agronomist.io
spec:
  group: agronomist.io
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            rego:
              type: string
            deployment:
              type: string

            min:
              type: integer
            max:
              type: integer

            maxStepUp:
              type: integer
            maxStepDown:
              type: integer

            upDelay:
              type: integer
            downDelay:
              type: integer

            interval:
              type: integer
        status:
          properties: {}
          type: object

  version: v1
  versions:
  - name: v1
    served: true
    storage: true

  scope: Namespaced
  names:
    plural: scalingpolicies
    singular: scalingpolicy
    kind: ScalingPolicy
    shortNames:
    - sp

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: scalingpolicystatuses.agronomist.io
spec:
  group: agronomist.io
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            error:
              type: string
        status:
          properties: {}
          type: object

  version: v1
  versions:
  - name: v1
    served: true
    storage: true

  scope: Namespaced
  names:
    plural: scalingpolicystatuses
    singular: scalingpolicystatus
    kind: ScalingPolicyStatus
    shortNames:
    - sps
